
# You can find all blocks in this list (supports only 1.14 blocks)
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum.constant.summary
#
# You can use my simplified biomes instead of default minecraft biomes.
# Simplified biomes include various biomes combined on the same basis
#
# For example simplified biome S_TAIGA combines biomes TAIGA, TAIGA_HILLS and TAIGA_MOUNTAINS
# List of my simplified biomes, that you can use:
# - S_FOREST (FOREST, WOODED_HILLS, FLOWER_FOREST)
# - S_BIRCH_FOREST (all birch and tall birch biomes)
# - S_DARK_FOREST (all dark forest biomes)
# - S_JUNGLE (all jungle biomes and bamboo jungle biomes)
# - S_SWAMP (all swamp biomes)
# - S_PLAINS (PLAINS and SUNFLOWER_PLAINS biomes)
# - S_DESERT (all desert biomes)
# - S_BADLANDS (all badlands biomes)
# - S_TUNDRA (all tundra and snowy taiga biomes)
# - S_TAIGA (all taiga biomes)
# - S_SAVANNA (all savanna biomes)
# - S_MOUNTAINS (all mountains biomes)
whitelisted-blocks:
    - BEETROOT_SEEDS:
          - 'S_PLAINS'
    - WHEAT_SEEDS:
          - 'S_PLAINS'
          - 'S_FOREST'
    - OAK_SAPLING:
          - 'S_FOREST'
          - 'S_PLAINS'
          - 'S_SWAMP'
    - BIRCH_SAPLING:
          - 'S_BIRCH_FOREST'
    - SPRUCE_SAPLING:
          - 'S_TAIGA'
          - 'S_TUNDRA'
    - DARK_OAK_SAPLING:
          - 'S_DARK_FOREST'
    - JUNGLE_SAPLING:
          - 'S_JUNGLE'
    - ACACIA_SAPLING:
          - 'S_SAVANNA'
    - BAMBOO_SAPLING:
          - 'BAMBOO_JUNGLE'
          - 'BAMBOO_JUNGLE_HILLS'
    - SWEET_BERRIES:
          - 'S_TAIGA'