name: BiomeLimits
author: iPiE

main: xyz.nifti.biomelimits.BiomeLimits
version: '${project.version}'
api-version: 1.13
depend: [ NiftiTranslate ]

commands:
    biomelimits:
        aliases: [ bl ]

permissions:
    biomelimits.bypass:
        default: false

    biomelimits.reload:
        default: op